# XWiki with Let's Encrypt in a Docker Compose

# Author
# hey, Iâ€™m Vladimir Mikhalev, but my friends call me Valdemar.

# My website with detailed IT guides: https://www.heyvaldemar.com/
# Follow me on YouTube: https://www.youtube.com/channel/UCf85kQ0u1sYTTTyKVpxrlyQ?sub_confirmation=1
# Follow me on Twitter: https://twitter.com/heyValdemar
# Follow me on Instagram: https://www.instagram.com/heyvaldemar/
# Follow me on Facebook: https://www.facebook.com/heyValdemarFB/
# Follow me on TikTok: https://www.tiktok.com/@heyvaldemar
# Follow me on [LinkedIn](https://www.linkedin.com/in/heyvaldemar/)
# Follow me on [GitHub](https://github.com/heyvaldemar)

# Communication
# Chat with IT pros on Discord: https://discord.com/invite/D7fGMYjdR9
# Chat with IT pros on Telegram: https://t.me/heyValdemarCOMchat
# Reach me at ask@sre.gg

# Give Thanks
# Support on GitHub: https://github.com/sponsors/heyValdemar
# Support on Patreon: https://www.patreon.com/heyValdemar
# Support on BuyMeaCoffee: https://www.buymeacoffee.com/heyValdemar
# Support on Ko-fi: https://ko-fi.com/heyValdemar
# Support on PayPal: https://www.paypal.com/paypalme/heyValdemarCOM

# Install Docker Engine and Docker Compose by following my guide: https://www.heyvaldemar.com/install-docker-engine-and-docker-compose-on-ubuntu-server/

# Run xwiki-restore-application-data.sh to restore application data if needed.
# Run xwiki-restore-database.sh to restore database if needed.

# Deploy XWiki server with a Docker Compose using the command:
# docker compose -f xwiki-traefik-letsencrypt-docker-compose.yml -p xwiki up -d

# Detailed installation guide can be found on my website: https://www.heyvaldemar.com/install-xwiki-with-docker-compose/

volumes:
  xwiki-data:
  xwiki-postgres:
  traefik-certificates:
  xwiki-data-backups:
  xwiki-postgres-backups:

services:
  postgres:
    # Image tag (replace with yours)
    image: postgres:14
    volumes:
      - xwiki-postgres:/var/lib/postgresql/data
    environment:
      # Database name (replace with yours)
      POSTGRES_DB: xwiki
      # Database user (replace with yours)
      POSTGRES_USER: xwikidbuser
      # Database password (replace with yours)
      POSTGRES_PASSWORD: b*!HJBJd4*q!L4qHpjD2K6!
      # Postgres root password (replace with yours)
      POSTGRES_ROOT_PASSWORD: yUN!y@6Ba.m!ZLkbkAX49y@
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  xwiki:
    # Image tag (replace with yours)
    image: xwiki:14.4-postgres-tomcat
    volumes:
      - xwiki-data:/usr/local/xwiki
    environment:
      DB_HOST: postgres
      # Database name (replace with yours)
      DB_DATABASE: xwiki
      # Database user (replace with yours)
      DB_USER: xwikidbuser
      # Database password (replace with yours)
      DB_PASSWORD: b*!HJBJd4*q!L4qHpjD2K6!
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - "traefik.enable=true"
      # XWiki URL (replace with yours)
      - "traefik.http.routers.xwiki.rule=Host(`xwiki.heyvaldemar.net`)"
      - "traefik.http.routers.xwiki.service=xwiki"
      - "traefik.http.routers.xwiki.entrypoints=websecure"
      - "traefik.http.services.xwiki.loadbalancer.server.port=8080"
      - "traefik.http.routers.xwiki.tls=true"
      - "traefik.http.routers.xwiki.tls.certresolver=letsencrypt"
      - "traefik.http.services.xwiki.loadbalancer.passhostheader=true"
      - "traefik.http.routers.xwiki.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      traefik:
        condition: service_healthy

  traefik:
    # Image tag (replace with yours)
    image: traefik:2.8
    command:
      - "--log.level=WARN"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--ping=true"
      - "--ping.entrypoint=ping"
      - "--entryPoints.ping.address=:8082"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # Email for Let's Encrypt (replace with yours)
      - "--certificatesresolvers.letsencrypt.acme.email=callvaldemar@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/etc/traefik/acme
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8082/ping","--spider"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - "traefik.enable=true"
      # Traefik URL (replace with yours)
      - "traefik.http.routers.dashboard.rule=Host(`traefik.xwiki.heyvaldemar.net`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.dashboard.loadbalancer.passhostheader=true"
      - "traefik.http.routers.dashboard.middlewares=authtraefik"
      # Basic Authentication for Traefik Dashboard
      # Username: traefikadmin (replace with yours)
      # Passwords must be encoded using MD5, SHA1, or BCrypt https://hostingcanada.org/htpasswd-generator/
      - "traefik.http.middlewares.authtraefik.basicauth.users=traefikadmin:$$2y$$10$$sMzJfirKC75x/hVpiINeZOiSm.Jkity9cn4KwNkRvO7hSQVFc5FLO"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    restart: unless-stopped

  backups:
    # Image tag (replace with yours)
    image: postgres:14
    # Database backups prune interval (replace with yours). Default is 7 days.
    # find /srv/xwiki-postgres/backups -type f -mtime +7 | xargs rm -f

    # Application data backups prune interval (replace with yours). Default is 7 days.
    # find /srv/xwiki-application-data/backups -type f -mtime +7 | xargs rm -f

    # XWiki backups interval (replace with yours). Default is 1 day.
    # sleep 24h

    # Run xwiki-restore-application-data.sh to restore application data if needed.
    # Run xwiki-restore-database.sh to restore database if needed.
    command: sh -c 'sleep 30m
             && while true; do
             PGPASSWORD="$$(echo $$POSTGRES_PASSWORD)"
             pg_dump
             -h postgres
             -p 5432
             -d xwikidb
             -U xwikidbuser | gzip > /srv/xwiki-postgres/backups/xwiki-postgres-backup-$$(date "+%Y-%m-%d_%H-%M").gz
             && tar -zcpf /srv/xwiki-application-data/backups/xwiki-application-data-backup-$$(date "+%Y-%m-%d_%H-%M").tar.gz /usr/local/xwiki
             && find /srv/xwiki-postgres/backups -type f -mtime +7 | xargs rm -f
             && find /srv/xwiki-application-data/backups -type f -mtime +7 | xargs rm -f;
             sleep 24h; done'
    volumes:
      - xwiki-data:/usr/local/xwiki
      # Application data backups location
      - xwiki-data-backups:/srv/xwiki-application-data/backups
      # Database backups location
      - xwiki-postgres-backups:/srv/xwiki-postgres/backups
    environment:
      # Database password (replace with yours)
      POSTGRES_PASSWORD: b*!HJBJd4*q!L4qHpjD2K6!
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      xwiki:
        condition: service_healthy
